default:
  image: python:3.7


stages:
  - test


lint:
  stage: test
  script:
    - pip list
    - pip install '.[test]'
    - pip list
    - black --check src tests
    - flake8
    - mypy


tests:
  stage: test
  script:
    - pip list
    - pip install '.[test]'
    - pip list
    - PKG_LOCATION=$(python -c "import os, metahopt; print(os.path.dirname(metahopt.__file__))")
    - pytest -v --cov "$PKG_LOCATION" --cov-report term tests
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
